# golangci-lint configuration for v2.x
# Documentation: https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m

# Formatters configuration (new in v2)
formatters:
  enable:
    - gofmt
    - goimports
    - gci

# Linters configuration
linters:
  enable-all: false
  disable-all: true
  enable:
    # Core quality & correctness
    - errcheck
    - govet
    - ineffassign
    - staticcheck  # Includes gosimple and stylecheck in v2
    - unused
    
    # Style linters
    - godot
    - whitespace
    
    # Modernization & best practices
    - usestdlibvars
    - nolintlint
    - predeclared
    - perfsprint
    
    # Error handling (important for oops usage)
    - errorlint
    - nilerr
    - nilnil
    - wrapcheck
    
    # Context & concurrency
    - noctx
    - copyloopvar  # Replaces exportloopref in v2
    
    # Code quality & maintainability
    - revive
    - goconst
    - misspell
    - unconvert
    - unparam
    - wastedassign
    
    # Security
    - gosec
    
    # Testing
    - thelper
    
    # Logging (for slog usage)
    - sloglint

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true
  
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
  
  staticcheck:
    checks: ["all"]
  
  gosec:
    excludes:
      - G104
  
  wrapcheck:
    ignorePackageGlobs:
      - backend.atomicledger.com/*
  
  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true
  
  usestdlibvars:
    http-method: true
    http-status-code: true
    time-weekday: true
    time-month: true
    time-layout: true
    crypto-hash: true
  
  sloglint:
    no-mixed-args: true
    no-global: "all"
    context: "all"
  
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true

formatters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(backend.atomicledger.com)

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - wrapcheck
        - noctx
    
    - path: pkg/di/providers\.go
      linters:
        - wrapcheck
